### PR TITLE
Fix serialization bug

### LINKED ISSUE #261: Bug in deserialization
Sorry @sunxd3 I should've caught this when you asked me to go over the PR. The order in which fields are pushed during `serialize` and popped during `deserialize` doesn't match
 
https://github.com/TuringLang/JuliaBUGS.jl/blob/f51144cfe8c7f33cc6bcd4ed7299d2b18c23f247/src/model.jl#L237-L254

This means that `deserialize` tries to run 
```julia
compile(transformed, model_def, data)
```
instead of the correct one.
```julia
compile(model_def, data, evaluation_env)
```

### Reproducible error:

Session 1
```julia
using JuliaBUGS
using Serialization

unid_model_def = @bugs begin
    for i in 1:2
        p[i] ~ dunif(0,1)
    end
    p_prod = p[1]*p[2]
    n_heads ~ dbin(p_prod, n_flips)
end
model = compile(unid_model_def, (;n_flips=10))
Serialization.serialize("m.jls", model)
```
Session 2
```julia
using JuliaBUGS
using Serialization

model = Serialization.deserialize("m.jls")
ERROR: MethodError: no method matching compile(::Bool, ::Expr, ::@NamedTuple{n_flips::Int64})

Closest candidates are:
  compile(::Expr, ::NamedTuple, ::NamedTuple)
   @ JuliaBUGS ~/.julia/packages/JuliaBUGS/fLZjP/src/JuliaBUGS.jl:154

Stacktrace:
  [1] deserialize(s::Serializer{IOStream}, ::Type{JuliaBUGS.BUGSModel{…}})
    @ JuliaBUGS ~/.julia/packages/JuliaBUGS/fLZjP/src/model.jl:253
  [2] handle_deserialize(s::Serializer{IOStream}, b::Int32)
    @ Serialization ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:878
  [3] deserialize(s::Serializer{IOStream})
    @ Serialization ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:814
  [4] handle_deserialize(s::Serializer{IOStream}, b::Int32)
    @ Serialization ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:920
  [5] deserialize
    @ ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:814 [inlined]
  [6] deserialize(s::IOStream)
    @ Serialization ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:801
  [7] open(f::typeof(deserialize), args::String; kwargs::@Kwargs{})
    @ Base ./io.jl:396
  [8] open
    @ ./io.jl:393 [inlined]
  [9] deserialize(filename::String)
    @ Serialization ~/.julia/juliaup/julia-1.10.7+0.x64.linux.gnu/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:811
 [10] top-level scope
    @ ~/projects/Pigeons.jl/test/temp.jl:5
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by miguelbiron**
Closes #261

### CODE REVIEW

**Comment by miguelbiron** [comment]
Lol I guess the way I wrote it is not standard. Gonna change that.

**Comment by miguelbiron** [comment]
I don't understand why the serialization test you wrote didn't pick up this bug though. Maybe if you are in the same session the serializer just gets the current object? would be weird.

**Comment by sunxd3** [comment]
No I think the test wasn't actually run, fixing at https://github.com/TuringLang/JuliaBUGS.jl/pull/263

thanks for suggesting looking into it

**Comment by sunxd3** [comment]
Sorry for before @miguelbiron the CI should be fixed now, could you uncomment the tests for serialization and see if they run?

**Comment by miguelbiron** [comment]
Will do

**Comment by miguelbiron** [comment]
Seems like activating the tests reduced coverage? Not sure how that could happen. And the benchmark issue seems [related to permissions](https://stackoverflow.com/a/76994510/5443023).

**Comment by sunxd3** [comment]
benchmark might error because BridgeStan is segfaulting on macOS, so as long as it runs, it's okay

**Review by sunxd3 — APPROVED** [review]
thanks!

**Comment by sunxd3** [comment]
@miguelbiron apologies I usually won't do this, but since this fixes a bug that's pretty bad, I am merging it into master now

**Comment by miguelbiron** [comment]
Hey @sunxd3 I didn't know you were waiting for me to merge! But I'm pretty sure I  didn't have permission to do that or I would've done that otherwise. Anyway, I'm glad it's fixed!

**Pull request merged**
