### PR TITLE
Update inprod(a,b)

### PR DESCRIPTION
**Pull request by serenlee**
I found that I have an error with current version inprod(a,b). * is not working for two vectors.

### CODE REVIEW

**Comment by sunxd3** [comment]
thanks!

**Comment by sunxd3** [comment]
@serenlee it looks like the formatting is failing but the CI is not working properly, it should be something like

```julia
return LinearAlgebra.dot(a, b)
```

also it would be great if you can add a simple test to file https://github.com/serenlee/JuliaBUGS.jl/blob/patch-1/test/bugs_primitives.jl

sorry for being pedantic, thanks a lot for this

**Comment by serenlee** [comment]
Hi @sunxd3 
Sorry for late response. For unknown reason, I didn’t get notification.

I am actually new to Julia test, - does current test work? Also, your code 
`return LinearAlgebra.dot(a, b) `
is the same as my current one. If you have any feedback, please let me know.

**Comment by sunxd3** [comment]
@serenlee the formatter CI is a bit strange -- it usually show suggestions, but it's not doing that now. I took the liberty to do the formatting, hope it's not offensive.

**Comment by sunxd3** [comment]
@serenlee thanks!

**Pull request merged**
